import { Barlow_Semi_Condensed } from "next/font/google";
import "./globals.css";
import GlobalProvider from "@/context/GlobalContext";

const barlow = Barlow_Semi_Condensed ({
  variable: "--font-barlow-semi-condensed",
  subsets: ["latin"],
  weight: ['600', '700'],
});


export const metadata = {
  title: "Rock-Paper-Scissors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalProvider>
      <body
        className={`${barlow.variable} font-semibold antialiased`}
      >
        {children}
      </body>
      </GlobalProvider>
    </html>
  );
}
